//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis.Elfie {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.Elfie.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided buffer wasn&apos;t big enough. It was {0:n0}, needed {1:n0}.
        /// </summary>
        internal static string BufferTooSmall {
            get {
                return ResourceManager.GetString("BufferTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database can&apos;t be searched until ConvertToImmutable is called..
        /// </summary>
        internal static string ConvertToImmutableRequired {
            get {
                return ResourceManager.GetString("ConvertToImmutableRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ancestor of type &apos;{0}&apos; was found above &apos;{1}&apos;..
        /// </summary>
        internal static string Database_NoAncestorOfType {
            get {
                return ResourceManager.GetString("Database_NoAncestorOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Tree is out-of-sync with associated array &apos;{0}&apos;.
        /// </summary>
        internal static string DatabaseArraysOutOfSync {
            get {
                return ResourceManager.GetString("DatabaseArraysOutOfSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database text format incorrect. Expected &apos;{0}&apos; at ({1},{2}), but found &apos;{3}&apos;..
        /// </summary>
        internal static string DatabaseCharacterUnexpected {
            get {
                return ResourceManager.GetString("DatabaseCharacterUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database format version wrong. Expected: {0}; Actual: {1}.
        /// </summary>
        internal static string DatabaseFormatVersionWrong {
            get {
                return ResourceManager.GetString("DatabaseFormatVersionWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database text format incorrect. Expected &apos;{0}&apos; at ({1},{2}), but line was only length {3}..
        /// </summary>
        internal static string DatabaseLineTooShort {
            get {
                return ResourceManager.GetString("DatabaseLineTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database text format incorrect. Second line should be an integer version. It was &quot;{0}&quot;.
        /// </summary>
        internal static string DatabaseVersionNotInteger {
            get {
                return ResourceManager.GetString("DatabaseVersionNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load &apos;{0}&apos;. No file or folder found at path..
        /// </summary>
        internal static string LoadEach_FileNotFound {
            get {
                return ResourceManager.GetString("LoadEach_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberDatabase file extension &apos;{0}&apos; is not yet supported..
        /// </summary>
        internal static string MemberDatabase_ExtensionNotSupported {
            get {
                return ResourceManager.GetString("MemberDatabase_ExtensionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Format error. Expected array length at position {0} but read {1}..
        /// </summary>
        internal static string ReadArrayLength_LengthInvalid {
            get {
                return ResourceManager.GetString("ReadArrayLength_LengthInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadPrimitiveArray found unexpected size; reading {0}[], expected element size {1}, read {2}..
        /// </summary>
        internal static string ReadPrimitiveArray_WrongElementSize {
            get {
                return ResourceManager.GetString("ReadPrimitiveArray_WrongElementSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading &apos;{0}&apos;: {1} {2}.
        /// </summary>
        internal static string TryFileRead_ExceptionDuringRead {
            get {
                return ResourceManager.GetString("TryFileRead_ExceptionDuringRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to support multi-byte character &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToSupportMultibyteCharacter {
            get {
                return ResourceManager.GetString("UnableToSupportMultibyteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized database version &apos;{0}&apos;..
        /// </summary>
        internal static string UnrecognizedDatabaseFormatVersion {
            get {
                return ResourceManager.GetString("UnrecognizedDatabaseFormatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WritePrimitiveArray could not write non-primitive array type &apos;{0}[]&apos;.
        /// </summary>
        internal static string WritePrimitiveArray_NoPrimitiveType {
            get {
                return ResourceManager.GetString("WritePrimitiveArray_NoPrimitiveType", resourceCulture);
            }
        }
    }
}
